export const QUERY_KEYS = {
  currentUser: ["currentUser"] as const,
  userPublicProfile: ["userPublicProfile"] as const,
  foryouEvents: ["foryouevents"] as const,
  eventDetails: ["eventDetails"] as const,
  transactionRef: ["transactionRef"] as const,
  ticketOrReg: ["ticketOrReg"] as const,
  myTickets: ["myTickets"] as const,
  myRegistrations: ["myRegistrations"] as const,
  getUserEvents: ["getUserEvents"] as const,
  carpoolDetails: ["carpoolDetails"] as const,
  carpoolForYou: ["carpoolForYou"] as const,
  eventCarpoolsPaginated: ["eventCarpoolsPaginated"] as const,
  carpoolChat: ["carpoolChat"] as const,
  eventImageStatus: ["eventImageStatus"] as const,

  getDashboard: ["dashboarddata"] as const,
  homeAdCards: ["homeAdCards"] as const,
  getEventDashboard: ["getEventDashboard"] as const,
  getDashboardEvents: ["getDashboardEvents"] as const,
  getShortcut: ["getShortcut"] as const,
  getShortcutEvent: ["getShortcutEvent"] as const,
  getPayments: ["getPayments"] as const,
  walletOverview: ["walletOverview"] as const,
  walletOnboarding: ["walletOnboarding"] as const,
  walletKyc: ["walletKyc"] as const,
  walletBanks: ["walletBanks"] as const,

  scannerStats: ["scannerStats"] as const,
  scanHistory: ["scanHistory"] as const,
  myScannerPermissions: ["myScannerPermissions"] as const,
  grantedScannerPermissions: ["grantedScannerPermissions"] as const,
  scannerUsersSearch: ["scannerUsersSearch"] as const,
  canScan: ["canScan"] as const,
};
